import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import ToastProvider from "@/components/ToastProvider";
import { NextAuthProvider } from "./provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { SidebarProvider } from "@/context/sidebaropen.context";
import { PriceProvider } from "@/context/pricestate.context";
import BgColorContainer from "@/components/sidebar/BgColorContainer";
import SidebarModal from "@/components/sidebar/SidebarModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <PriceProvider>
            <Navbar session={session} />
            <ToastProvider />
            <SidebarModal session={session} />
            <NextAuthProvider>{children}</NextAuthProvider>
          </PriceProvider>
        </SidebarProvider>
        <Script
          type="text/javascript"
          src="//dapi.kakao.com/v2/maps/sdk.js?appkey=72967a1e2143a6d338837326d597b5be&libraries=services,clusterer&autoload=false"
        ></Script>
      </body>
    </html>
  );
}
